// automatically generated by the FlatBuffers compiler, do not modify

package com.phraser.schema.phraser;

@SuppressWarnings("unused")
public final class BlockType {
  private BlockType() { }
  public static final byte Unknown = 0;
  public static final byte FoldersBlock = 1;
  public static final byte SymbolSetsBlock = 2;
  public static final byte PhraseTemplatesBlock = 3;
  public static final byte PhraseBlock = 4;
  public static final byte KeyBlock = 5;

  public static final String[] names = { "Unknown", "FoldersBlock", "SymbolSetsBlock", "PhraseTemplatesBlock", "PhraseBlock", "KeyBlock", };

  public static String name(int e) { return names[e]; }
}

