// automatically generated by the FlatBuffers compiler, do not modify

package com.phraser.schema.phraser;

@SuppressWarnings("unused")
public final class Icon {
  private Icon() { }
  public static final byte Unknown = 0;
  public static final byte Key = 1;
  public static final byte Login = 2;
  public static final byte Asterisk = 3;
  public static final byte Lock = 4;
  public static final byte Aa = 5;
  public static final byte Star = 6;
  public static final byte Settings = 7;
  public static final byte Folder = 8;
  public static final byte ToParentFolder = 9;
  public static final byte LookingGlass = 10;
  public static final byte LTTriangle = 11;
  public static final byte GTTriangle = 12;
  public static final byte TextOut = 13;
  public static final byte Ledger = 14;
  public static final byte PlusMinus = 15;
  public static final byte Stars = 16;
  public static final byte Message = 17;
  public static final byte Quote = 18;
  public static final byte Question = 19;
  public static final byte Plus = 20;
  public static final byte Minus = 21;
  public static final byte X = 22;
  public static final byte Check = 23;
  public static final byte Copy = 24;
  public static final byte Download = 25;
  public static final byte Upload = 26;
  public static final byte Skull = 27;

  public static final String[] names = { "Unknown", "Key", "Login", "Asterisk", "Lock", "Aa", "Star", "Settings", "Folder", "ToParentFolder", "LookingGlass", "LTTriangle", "GTTriangle", "TextOut", "Ledger", "PlusMinus", "Stars", "Message", "Quote", "Question", "Plus", "Minus", "X", "Check", "Copy", "Download", "Upload", "Skull", };

  public static String name(int e) { return names[e]; }
}

