// automatically generated by the FlatBuffers compiler, do not modify

package com.phraser.schema.phraser;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class KeyBlock extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static KeyBlock getRootAsKeyBlock(ByteBuffer _bb) { return getRootAsKeyBlock(_bb, new KeyBlock()); }
  public static KeyBlock getRootAsKeyBlock(ByteBuffer _bb, KeyBlock obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public KeyBlock __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public StoreBlock block() { return block(new StoreBlock()); }
  public StoreBlock block(StoreBlock obj) { int o = __offset(4); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public byte key(int j) { int o = __offset(6); return o != 0 ? bb.get(__vector(o) + j * 1) : 0; }
  public int keyLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector keyVector() { return keyVector(new ByteVector()); }
  public ByteVector keyVector(ByteVector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer keyAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer keyInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public boolean mutateKey(int j, byte key) { int o = __offset(6); if (o != 0) { bb.put(__vector(o) + j * 1, key); return true; } else { return false; } }
  public byte iv(int j) { int o = __offset(8); return o != 0 ? bb.get(__vector(o) + j * 1) : 0; }
  public int ivLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector ivVector() { return ivVector(new ByteVector()); }
  public ByteVector ivVector(ByteVector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer ivAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer ivInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public boolean mutateIv(int j, byte iv) { int o = __offset(8); if (o != 0) { bb.put(__vector(o) + j * 1, iv); return true; } else { return false; } }

  public static void startKeyBlock(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addBlock(FlatBufferBuilder builder, int blockOffset) { builder.addStruct(0, blockOffset, 0); }
  public static void addKey(FlatBufferBuilder builder, int keyOffset) { builder.addOffset(1, keyOffset, 0); }
  public static int createKeyVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createKeyVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startKeyVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static void addIv(FlatBufferBuilder builder, int ivOffset) { builder.addOffset(2, ivOffset, 0); }
  public static int createIvVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createIvVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startIvVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static int endKeyBlock(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public KeyBlock get(int j) { return get(new KeyBlock(), j); }
    public KeyBlock get(KeyBlock obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

