// automatically generated by the FlatBuffers compiler, do not modify

package com.phraser.schema.phraser;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class PhraseTemplate extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static PhraseTemplate getRootAsPhraseTemplate(ByteBuffer _bb) { return getRootAsPhraseTemplate(_bb, new PhraseTemplate()); }
  public static PhraseTemplate getRootAsPhraseTemplate(ByteBuffer _bb, PhraseTemplate obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PhraseTemplate __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int phraseTemplateId() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public boolean mutatePhraseTemplateId(int phrase_template_id) { int o = __offset(4); if (o != 0) { bb.putShort(o + bb_pos, (short) phrase_template_id); return true; } else { return false; } }
  public long minLength() { int o = __offset(6); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public boolean mutateMinLength(long min_length) { int o = __offset(6); if (o != 0) { bb.putInt(o + bb_pos, (int) min_length); return true; } else { return false; } }
  public long maxLength() { int o = __offset(8); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public boolean mutateMaxLength(long max_length) { int o = __offset(8); if (o != 0) { bb.putInt(o + bb_pos, (int) max_length); return true; } else { return false; } }
  public String phraseTemplateName() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer phraseTemplateNameAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer phraseTemplateNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public int symbolSetIds(int j) { int o = __offset(12); return o != 0 ? bb.getShort(__vector(o) + j * 2) & 0xFFFF : 0; }
  public int symbolSetIdsLength() { int o = __offset(12); return o != 0 ? __vector_len(o) : 0; }
  public ShortVector symbolSetIdsVector() { return symbolSetIdsVector(new ShortVector()); }
  public ShortVector symbolSetIdsVector(ShortVector obj) { int o = __offset(12); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer symbolSetIdsAsByteBuffer() { return __vector_as_bytebuffer(12, 2); }
  public ByteBuffer symbolSetIdsInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 2); }
  public boolean mutateSymbolSetIds(int j, int symbol_set_ids) { int o = __offset(12); if (o != 0) { bb.putShort(__vector(o) + j * 2, (short) symbol_set_ids); return true; } else { return false; } }

  public static int createPhraseTemplate(FlatBufferBuilder builder,
      int phraseTemplateId,
      long minLength,
      long maxLength,
      int phraseTemplateNameOffset,
      int symbolSetIdsOffset) {
    builder.startTable(5);
    PhraseTemplate.addSymbolSetIds(builder, symbolSetIdsOffset);
    PhraseTemplate.addPhraseTemplateName(builder, phraseTemplateNameOffset);
    PhraseTemplate.addMaxLength(builder, maxLength);
    PhraseTemplate.addMinLength(builder, minLength);
    PhraseTemplate.addPhraseTemplateId(builder, phraseTemplateId);
    return PhraseTemplate.endPhraseTemplate(builder);
  }

  public static void startPhraseTemplate(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addPhraseTemplateId(FlatBufferBuilder builder, int phraseTemplateId) { builder.addShort(0, (short) phraseTemplateId, (short) 0); }
  public static void addMinLength(FlatBufferBuilder builder, long minLength) { builder.addInt(1, (int) minLength, (int) 0L); }
  public static void addMaxLength(FlatBufferBuilder builder, long maxLength) { builder.addInt(2, (int) maxLength, (int) 0L); }
  public static void addPhraseTemplateName(FlatBufferBuilder builder, int phraseTemplateNameOffset) { builder.addOffset(3, phraseTemplateNameOffset, 0); }
  public static void addSymbolSetIds(FlatBufferBuilder builder, int symbolSetIdsOffset) { builder.addOffset(4, symbolSetIdsOffset, 0); }
  public static int createSymbolSetIdsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(2, data.length, 2); for (int i = data.length - 1; i >= 0; i--) builder.addShort((short) data[i]); return builder.endVector(); }
  public static void startSymbolSetIdsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(2, numElems, 2); }
  public static int endPhraseTemplate(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PhraseTemplate get(int j) { return get(new PhraseTemplate(), j); }
    public PhraseTemplate get(PhraseTemplate obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

