// automatically generated by the FlatBuffers compiler, do not modify

package com.phraser.schema.phraser;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class StoreWordValue extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static StoreWordValue getRootAsStoreWordValue(ByteBuffer _bb) { return getRootAsStoreWordValue(_bb, new StoreWordValue()); }
  public static StoreWordValue getRootAsStoreWordValue(ByteBuffer _bb, StoreWordValue obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public StoreWordValue __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int phraseTemplateId() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public boolean mutatePhraseTemplateId(int phrase_template_id) { int o = __offset(4); if (o != 0) { bb.putShort(o + bb_pos, (short) phrase_template_id); return true; } else { return false; } }
  public String wordValue() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer wordValueAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer wordValueInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createStoreWordValue(FlatBufferBuilder builder,
      int phraseTemplateId,
      int wordValueOffset) {
    builder.startTable(2);
    StoreWordValue.addWordValue(builder, wordValueOffset);
    StoreWordValue.addPhraseTemplateId(builder, phraseTemplateId);
    return StoreWordValue.endStoreWordValue(builder);
  }

  public static void startStoreWordValue(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addPhraseTemplateId(FlatBufferBuilder builder, int phraseTemplateId) { builder.addShort(0, (short) phraseTemplateId, (short) 0); }
  public static void addWordValue(FlatBufferBuilder builder, int wordValueOffset) { builder.addOffset(1, wordValueOffset, 0); }
  public static int endStoreWordValue(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public StoreWordValue get(int j) { return get(new StoreWordValue(), j); }
    public StoreWordValue get(StoreWordValue obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

