// automatically generated by the FlatBuffers compiler, do not modify

package com.phraser.schema.phraser;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class SymbolSetsBlock extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static SymbolSetsBlock getRootAsSymbolSetsBlock(ByteBuffer _bb) { return getRootAsSymbolSetsBlock(_bb, new SymbolSetsBlock()); }
  public static SymbolSetsBlock getRootAsSymbolSetsBlock(ByteBuffer _bb, SymbolSetsBlock obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SymbolSetsBlock __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public StoreBlock block() { return block(new StoreBlock()); }
  public StoreBlock block(StoreBlock obj) { int o = __offset(4); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public SymbolSet symbolSets(int j) { return symbolSets(new SymbolSet(), j); }
  public SymbolSet symbolSets(SymbolSet obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int symbolSetsLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public SymbolSet.Vector symbolSetsVector() { return symbolSetsVector(new SymbolSet.Vector()); }
  public SymbolSet.Vector symbolSetsVector(SymbolSet.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static void startSymbolSetsBlock(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addBlock(FlatBufferBuilder builder, int blockOffset) { builder.addStruct(0, blockOffset, 0); }
  public static void addSymbolSets(FlatBufferBuilder builder, int symbolSetsOffset) { builder.addOffset(1, symbolSetsOffset, 0); }
  public static int createSymbolSetsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startSymbolSetsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endSymbolSetsBlock(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SymbolSetsBlock get(int j) { return get(new SymbolSetsBlock(), j); }
    public SymbolSetsBlock get(SymbolSetsBlock obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

