// automatically generated by the FlatBuffers compiler, do not modify

package com.phraser.schema.phraser;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class WordTemplateRef extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static WordTemplateRef getRootAsWordTemplateRef(ByteBuffer _bb) { return getRootAsWordTemplateRef(_bb, new WordTemplateRef()); }
  public static WordTemplateRef getRootAsWordTemplateRef(ByteBuffer _bb, WordTemplateRef obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public WordTemplateRef __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int wordTemplateId() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public boolean mutateWordTemplateId(int word_template_id) { int o = __offset(4); if (o != 0) { bb.putShort(o + bb_pos, (short) word_template_id); return true; } else { return false; } }
  public byte wordTemplateOrdinal() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public boolean mutateWordTemplateOrdinal(byte word_template_ordinal) { int o = __offset(6); if (o != 0) { bb.put(o + bb_pos, word_template_ordinal); return true; } else { return false; } }

  public static int createWordTemplateRef(FlatBufferBuilder builder,
      int wordTemplateId,
      byte wordTemplateOrdinal) {
    builder.startTable(2);
    WordTemplateRef.addWordTemplateId(builder, wordTemplateId);
    WordTemplateRef.addWordTemplateOrdinal(builder, wordTemplateOrdinal);
    return WordTemplateRef.endWordTemplateRef(builder);
  }

  public static void startWordTemplateRef(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addWordTemplateId(FlatBufferBuilder builder, int wordTemplateId) { builder.addShort(0, (short) wordTemplateId, (short) 0); }
  public static void addWordTemplateOrdinal(FlatBufferBuilder builder, byte wordTemplateOrdinal) { builder.addByte(1, wordTemplateOrdinal, 0); }
  public static int endWordTemplateRef(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public WordTemplateRef get(int j) { return get(new WordTemplateRef(), j); }
    public WordTemplateRef get(WordTemplateRef obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

