name: Release PhraserManager

# This triggers workflow on tag push
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allow write access to repository contents

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up JDK 17 with Temurin
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Do wrapper
        run: gradle wrapper

      - name: Build JAR file with Gradle
        run: ./gradlew shadowJar

      - name: ls
        run: ls -al PhraserManager/build/libs

      - name: sha256
        run: openssl sha256 PhraserManager/build/libs/*

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload x64 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: PhraserManager/build/libs/PhraserManager-0.0.4-all.jar
          asset_name: PhraserManager-0.0.4-all.jar
          asset_content_type: application/jar
